export const login = `
mutation Login($facebookId:String,$email:String,$password:String,$type:String!,$appleId:String,$name:String,$notificationToken:String){
    login(facebookId:$facebookId,email:$email,password:$password,type:$type,appleId:$appleId,name:$name,notificationToken:$notificationToken){
     userId
     token
     tokenExpiration
     isActive
     name
     email
     phone
   }
}
`

export const Deactivate = `
  mutation deactivated($isActive: Boolean!, $email: String!) {
    Deactivate(isActive: $isActive,email: $email) {
      isActive
    }
  }
  `

export const categories = `query{
  categories{
    _id
    title
    image
  }
}`
export const subCategories = `query SubCategoriesById($id: String!){
  subCategoriesById(id:$id){
    _id
    title
    
  }
}`

export const itemsBySubCategory = `query ItemsByCategory($subCategory: [String!], $min: Float, $max: Float, $condition: String, $sort: String){
  itemsByCategory(subCategory:$subCategory,min:$min, max:$max, condition:$condition, sort: $sort){
    _id
    itemId
    title
    description
    condition
    subCategory{
      _id
      title
      category{
        _id
        title
      }
    }
    zone{
      _id
      title
      description
      location{
        coordinates
      }
    }
    status
    likesCount
    images
    price
    user{
      _id
      name
      phone
      callingCode
      showPhone
      createdAt
      followers{
        _id
      }
      following{
        _id
      }
      likes{
        _id
      }
    }
    address{
      _id
      location{
        coordinates
      }
      address
    }
    createdAt
  }
}`

export const nearByItems = `query NearByItems($latitude: Float,$longitude: Float, $zone: String){
  nearByItems(latitude: $latitude,longitude: $longitude,zone: $zone){
    _id
    itemId
    title
    description
    condition
    subCategory{
      _id
      title
      category{
        _id
        title
      }
    }
    zone{
      _id
      title
      description
      location{
        coordinates
      }
    }
    status
    likesCount
    images
    price
    user{
      _id
      name
      phone
      callingCode
      showPhone
      createdAt
      followers{
        _id
      }
      following{
        _id
      }
      likes{
        _id
      }
    }
    address{
      _id
      location{
        coordinates
      }
      address
    }
    createdAt
  }
}`

export const addToFavourites = `mutation AddToFavourites($item: String){
  addToFavourites(item:$item){
    _id
    likes{
      _id
    itemId
    title
    description
    condition
    subCategory{
      _id
      title
      category{
        _id
        title
      }
    }
    zone{
      _id
      title
      description
      location{
        coordinates
      }
    }
    status
    likesCount
    images
    price
    user{
      _id
      name
      phone
      callingCode
      showPhone
      createdAt
      followers{
        _id
      }
      following{
        _id
      }
      likes{
        _id
      }
    }
    address{
      _id
      location{
        coordinates
      }
      address
    }
    createdAt
    }
  }
}`

export const likes = `query{
  likes{
    _id
    itemId
    title
    description
    condition
    subCategory{
      _id
      title
      category{
        _id
        title
      }
    }
    zone{
      _id
      title
      description
      location{
        coordinates
      }
    }
    status
    likesCount
    images
    price
    user{
      _id
      name
      phone
      callingCode
      showPhone
      createdAt
      followers{
        _id
      }
      following{
        _id
      }
      likes{
        _id
      }
    }
    address{
      _id
      location{
        coordinates
      }
      address
    }
    createdAt
  }
}`

export const getUser = `query User($id: String!){
  user(id:$id){
    _id
    name
    phone
    email
    createdAt
    followers{
      _id
      name
    }
    following{
      _id
      name
    }
  }
}` 

export const profile = `
  query{
    profile{
        _id
        name
        phone
        email
        description
        notificationToken
        showPhone
        countryCode
        callingCode
        googleEmail
        createdAt
        isOfferNotification
        notifications{
          _id
          order
          message
          status
          date
        }
        followers{
          _id
          name
        }
        following{
          _id
          name
        }
        likes{
          _id
    itemId
    title
    description
    condition
    subCategory{
      _id
      title
      category{
        _id
        title
      }
    }
    zone{
      _id
      title
      description
      location{
        coordinates
      }
    }
    status
    likesCount
    images
    price
    user{
      _id
      name
      phone
      callingCode
      showPhone
      createdAt
      followers{
        _id
      }
      following{
        _id
      }
      likes{
        _id
      }
    }
    address{
      _id
      location{
        coordinates
      }
      address
    }
    createdAt
        }
      }
  }`

  export const updateUser = `mutation UpdateUser($userInput:UserInput!){
    updateUser(userInput:$userInput){
      _id
      name
      phone
      email
      description
      notificationToken
      showPhone
      countryCode
      callingCode
      googleEmail
      followers{
        _id
        name
      }
      following{
        _id
        name
      }
      likes{
        _id
        itemId
        images
        price
        subCategory{
          _id
          title
        }
      }
    }
  }`

  export const itemsByUser = `query{
    itemsByUser{
      _id
      itemId
      title
      description
      condition
      subCategory{
        _id
        title
      }
      zone{
        _id
        title
        description
        location{
          coordinates
        }
      }
      status
      likesCount
      images
      price
      user{
        _id
        name
        phone
        showPhone
        callingCode
        createdAt
        followers{
          _id
        }
        following{
          _id
        }
        likes{
          _id
        }
      }
      address{
        _id
        address
        location{
          coordinates
        }
      }
      createdAt
    }
  }`

  export const getConfiguration = `query Configuration{
    configuration{
      _id
      itemPrefix
      currency
      currencySymbol
    }
  }`

  export const zones = `query{
    zones{
     _id
     title
     description
     location{
       coordinates
     }
   }
   }`


   export const followUser = `mutation FollowUser($followStatus: Boolean!, $userId: String!){
    followUser(followStatus:$followStatus,userId:$userId){
      _id
      followers{
        _id
        name
        phone
        email
        showEmail
        showPhone
        callingCode
      }
      following{
        _id
        name
        phone
        email
        showEmail
        showPhone
        callingCode
      }
    }
  }`

  export const createAd = `mutation CreateItem($item:ItemInput!){
    createItem(item:$item){
      _id
      itemId
      title
      description
      condition
      subCategory{
        _id
        title
      }
      zone{
        _id
        title
        description
        location{
          coordinates
        }
      }
      status
      likesCount
      images
      price
      user{
        _id
        name
        phone
        showPhone
        callingCode
        createdAt
        followers{
          _id
        }
        following{
          _id
        }
        likes{
          _id
        }
      }
      address{
        _id
        address
        location{
          coordinates
        }
      }
      createdAt
    }
  }`

  export const editAd = `mutation EditItem($item:ItemInput!){
    editItem(item:$item){
      _id
      itemId
      title
      description
      condition
      subCategory{
        _id
        title
      }
      zone{
        _id
        title
        description
        location{
          coordinates
        }
      }
      status
      likesCount
      images
      price
      user{
        _id
        name
        phone
        showPhone
        callingCode
        createdAt
        followers{
          _id
        }
        following{
          _id
        }
        likes{
          _id
        }
      }
      address{
        _id
        address
        location{
          coordinates
        }
      }
      createdAt
    }
  }`


 export const updateItemStatus = `mutation UpdateItemStatus($id: String!, $status: String!){
    updateItemStatus(id:$id,status:$status){
      _id
    itemId
    title
    description
    condition
    subCategory{
      _id
      title
      category{
        _id
        title
      }
    }
    zone{
      _id
      title
      description
      location{
        coordinates
      }
    }
    status
    likesCount
    images
    price
    user{
      _id
      name
      phone
      callingCode
      showPhone
      createdAt
      followers{
        _id
      }
      following{
        _id
      }
      likes{
        _id
      }
    }
    address{
      _id
      location{
        coordinates
      }
      address
    }
    createdAt
    }
  }`

  export const updateNotificationStatus = `
    mutation UpdateNotificationStatus($offerNotification:Boolean!){
      updateNotificationStatus(offerNotification:$offerNotification){
        _id
        notificationToken
        isOfferNotification
      }
    }`

    export const pushToken = `mutation PushToken($token:String!){
      pushToken(token:$token){
        _id
        notificationToken
      }
    }`